### ISSUE TITLE
Comments after Metadata don’t work

### ISSUE THREAD

**Issue by ChristophLabacher** [opencolor-tools/opencolor-js#30]
```
List:
  oct/:
    view: List
    showValue: true
    swatchShape: CIRCLE //[CIRCLE/SQUARE/STRECHED]
```
`Unexpected 'COMMENT'`
